---
- hosts: test
  become: true
  become_user: root
  tasks:
  - name: Add Entry in Sudoers file
    lineinfile:
      path: /etc/sudoers
      state: present
      backup: yes
      line: 'progress ALL=NOPASSWD: /bin/systemctl  status httpd'
      validate: '/usr/sbin/visudo -cf %s'

