---
- hosts: localhost
  become: true
  become_user: root

  tasks:
    - debug:
        msg: play1
  
    - name: Creating the tarball
      command: tar cvzf /apps/ansible/zabbixscripts.tgz /apps/ansible/zabbixscripts
